# ==============================================================================
# link_extraction_RUNFILE.R
# script to call functions to convert word docs to html then extract and process
# hyperlinks found in the document
# J Gerulaitis, 24/08/2022
# ==============================================================================

# read in libraries
require(data.table)
require(dplyr)
require(httr)
require(pdftools)
require(rlang)
require(rmarkdown)
require(rstudioapi)  
require(rvest)
require(stringr)

# set working directory to be folder containing this file
setwd(dirname(getActiveDocumentContext()$path)) 

# pull in bespoke functions
source("word_to_html_rmd.R")
source("html_link_extractor.R")
source("link_processing.R")

# ------------------------------------------------------------------------------
# USER INPUTS:
# ------------------------------------------------------------------------------

# location of folder containing word doc(s) to be converted to html/rmarkdown (rmd)
input_path <- "C:/Users/GerulaitisJoanna/OneDrive - Planning Inspectorate/Admin/Data_Architecture/Knowledge_Service/word/"

# parent directory to save converted word files (html and rmd versions) and lists of extracted links in
# (subfolders will be generated by this script)
output_dir <- "C:/Users/GerulaitisJoanna/OneDrive - Planning Inspectorate/Admin/Data_Architecture/Knowledge_Service/"

# toggle to indicate whether to run word -> html/rmd function (TRUE/FALSE)
word_to_html_rmd_toggle <- TRUE

# toggle to indicate whether to run hyperlink extraction from html docs (TRUE/FALSE)
extract_hyperlinks_toggle <- TRUE

# toggle to indicate whether to run processing of hyperlinks (TRUE/FALSE)
link_processing_toggle <- TRUE

# ------------------------------------------------------------------------------

# derive output path for converted docx files from output_dir
output_path_html_rmd <- paste0(output_dir, "html_rmd/")

# create output folder for html/rmd files if doesn't already exist, within output_dir
dir.create(file.path(output_dir, "html_rmd/"), showWarnings = FALSE)

# derive output path for lists of hyperlinks to be saved from output_dir
output_path_csv <- paste0(output_dir, "csv/")

# create output folder for csv files if doesn't already exist, within output_dir
dir.create(file.path(output_dir, "csv"), showWarnings = FALSE)

# derive output path for lists of hyperlinks to be saved from output_dir
output_path_csv_processed <- paste0(output_dir, "csv_processed/")

# create output folder for csv files if doesn't already exist, within output_dir
dir.create(file.path(output_dir, "csv_processed"), showWarnings = FALSE)

if(word_to_html_rmd_toggle){
  
  # call function to convert word doc(s) to html/rmd
  # (check that files have been created in the output_path as expected after running)
  word_to_html_rmd(input_path, output_path_html_rmd)
}

if(extract_hyperlinks_toggle){
  
  # call function to extract external hyperlinks from html files
  html_link_extractor(output_path_html_rmd, output_path_csv)
}

if(link_processing_toggle){
  
  # call function to process/label hyperlinks extracted from html files
  link_processing(output_path_csv, output_path_csv_processed)
}



